import { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    name: 'MANCINI ATV 250 CC MOD R',
    slug: 'mancini-atv-250-cc-mod-r',
    price: 34990,
    salePrice: 27990,
    description: 'Gjør deg klar for ekte kjøreglede med Mancini ATV 250 Racing. Denne høyytelses-ATV-en er bygget for deg som ønsker kraft, kontroll og en racing-opplevelse, enten du kjører på bane, i skogen eller på grusveier. Med brede offroad-dekk, lavt tyngdepunkt og kraftige skivebremser får du presis håndtering og trygg kjøring selv i krevende terreng.',
    specs: {
      'Motor': '250CC 4-takts vannavkjølt',
      'Girkasse': 'Manuell',
      'Start': 'Elektrisk start',
      'Fjæring': 'Justerbar',
      'Design': 'Sporty racingdesign',
    },
    images: [
      '/images/products/250-cc-atv-vannavkj-lt-250cc-firehjulinger-mancini-250-atv-deler-orange-black/7aee4aa9-eb47-495e-bea4-a70f74748e87.jpeg',
      '/images/products/250-cc-atv-vannavkj-lt-250cc-firehjulinger-mancini-250-atv-deler-orange-black/318c1da1-bfe2-45cd-b4f8-c35076dc8c11.jpeg',
      '/images/products/250-cc-atv-vannavkj-lt-250cc-firehjulinger-mancini-250-atv-deler-orange-black/8ee9b420-0113-4dc7-ab14-496397a43a18.jpeg',
      '/images/products/250-cc-atv-vannavkj-lt-250cc-firehjulinger-mancini-250-atv-deler-orange-black/atv250cc.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '250cc',
    ageGroup: '10-12',
    color: 'orange-black',
  },
  {
    id: '2',
    name: 'ATV Farmer 125cc sort speedometer',
    slug: 'atv-farmer125cc-sort-speedometer',
    price: 15990,
    salePrice: 14990,
    description: 'ATV Farmer 125cc er utstyrt med kraftige 8" dekk, firetakt motor og har et tøft utseende. Denne modellen har dødmannsknapp, ledlys og display med speedometer. 1+1 gir fremover og revers (ingen clutch) — passer best for aldersgruppen ca 7–16 år.',
    specs: {
      'Motor': '125cc 4-takt',
      'Sylindertype': 'Ensylindret luftavkjølt',
      'Start': 'Elektrisk start med batteri',
      'Girkasse': 'F-N-R Revers (1+1), ingen clutch, semiautomatisk',
      'Drivverk': 'Kjededrift',
      'Forbremse': 'Skivebremse',
      'Bakbremse': 'Hydraulisk skivebremse',
      'Dekk foran': '19×7-8',
      'Dekk bak': '18×9.5-8',
      'Batteri': '12V / 6,5Ah',
      'Bensintank': '3 L',
      'Maks hastighet': '60 km/h (justerbar ned til 6 km/h)',
      'Mål LxBxH': '134×99×78 cm',
      'Nettovekt': '105 kg',
      'Bruttovekt': '115 kg',
    },
    images: [
      '/images/products/at-farmer125-cc-blacl/atv_125_2.jpg',
      '/images/products/at-farmer125-cc-blacl/atv125cc20.jpg',
      '/images/products/at-farmer125-cc-blacl/atv_125_1.jpg',
      '/images/products/at-farmer125-cc-blacl/atv_125_3.jpg',
      '/images/products/at-farmer125-cc-blacl/atv_125_4.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '125cc',
    ageGroup: '7-10',
    color: 'black',
  },
  {
    id: '3',
    name: 'ATV Farmer 125cc rød speedometer hengerfeste',
    slug: 'atv-farmer125cc-rod-speedometer-hengerfeste',
    price: 15990,
    salePrice: 14990,
    description: 'ATV Farmer 125cc er utstyrt med kraftige 8" dekk, firetakt motor og har et tøft utseende. Denne modellen har dødmannsknapp, ledlys og display med speedometer og hengerfeste. 1+1: Fremover, nøytral og revers (ingen clutch) — passer best for aldersgruppen ca 7–16 år.',
    specs: {
      'Motor': '125cc 4-takt',
      'Sylindertype': 'Ensylindret luftavkjølt',
      'Start': 'Elektrisk start med batteri',
      'Girkasse': 'F-N-R Revers (1+1), ingen clutch, semiautomatisk',
      'Drivverk': 'Kjededrift',
      'Forbremse': 'Skivebremser',
      'Bakbremse': 'Hydraulisk skivebremse',
      'Dekk foran': '19×7-8',
      'Dekk bak': '18×9.5-8',
      'Batteri': '12V / 6,5Ah',
      'Bensintank': '3 L',
      'Tilbehør': 'Hengerfeste',
      'Maks hastighet': '60 km/h (justerbar ned til 6 km/h)',
      'Mål LxBxH': '134×99×78 cm',
      'Nettovekt': '105 kg',
      'Bruttovekt': '115 kg',
    },
    images: [
      '/images/products/at-farmer125-cc-red/0f725caf001537252f97e2e83643f12c.jpeg',
      '/images/products/at-farmer125-cc-red/86c89627ed3de2d5c1c2b546c9ec8bec.jpeg',
      '/images/products/at-farmer125-cc-red/a789210a8c4a5a029c8087863e82ba00.jpeg',
      '/images/products/at-farmer125-cc-red/af546cbee9922495f8f0de607b2534e3.jpeg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '125cc',
    ageGroup: '7-10',
    color: 'red',
  },
  {
    id: '4',
    name: 'ATV Predator sort speedometer hengerfeste',
    slug: 'atv-predator-sort-speedometer-hengerfeste',
    price: 16990,
    salePrice: 15990,
    description: 'ATV Predator 125cc er utstyrt med kraftige 8" dekk, firetakt motor og har et tøft utseende. Denne modellen har dødmannsknapp, ledlys og display med speedometer. 3+1: 3 gir fremover og revers (ingen clutch). Denne passer best for aldersgruppen ca 8–16 år.',
    specs: {
      'Motor': '125CC 4-takt',
      'Dekk': '8"',
      'Girkasse': '3+1 (3 gir fremover og revers, ingen clutch)',
      'Tilleggsutstyr': 'Dødmannsknapp, LED-lys, display med speedometer, hengerfeste',
    },
    images: [
      '/images/products/atv-predator-125-cc-black-2/atv125cc5.jpg',
      '/images/products/atv-predator-125-cc-black-2/atv125cc6.jpg',
      '/images/products/atv-predator-125-cc-black-2/atv125cc10.jpg',
      '/images/products/atv-predator-125-cc-black-2/atv125cc12.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '125cc',
    ageGroup: '7-10',
    color: 'black',
  },
  {
    id: '5',
    name: 'Can-Am Renegade Firhjuling for barn 12V',
    slug: 'can-am-renegade-firhjuling-for-barn-12v',
    price: 3798,
    salePrice: null,
    description: 'Stilig og trygg elbil for barn – fullpakket med morsomme funksjoner! Bilen har EVA-hjul for jevn kjøring, LED-lys, MP3-spiller, USB-inngang og fjæringssystem. Startes enkelt med knapp. Perfekt gave til små sjåfører med store drømmer!',
    specs: {
      'Bilens størrelse': '108 × 60,8 × 64 cm',
      'Bruttovekt': '21 kg',
      'Nettovekt': '17 kg',
      'Batteri': '12V 7AH × 1',
      'Motor': '550# × 2',
      'Funksjoner': 'EVA-hjul, MP3/musikk, USB/Radio, LED-lys, Fjæringssystem',
    },
    images: [
      '/images/products/can-am-renegade-firhjuling-for-barn-12v/083925a1da22a14b1109622e5c65a67a.jpeg',
      '/images/products/can-am-renegade-firhjuling-for-barn-12v/21561c569265e265d416e5bb580370e8.jpeg',
      '/images/products/can-am-renegade-firhjuling-for-barn-12v/2c3a29c43e1cb199afd704853a6e05f5.jpeg',
      '/images/products/can-am-renegade-firhjuling-for-barn-12v/318ae197c6d5a41ca5937ec0c79f96b9.jpeg',
    ],
    video: null,
    category: 'elektrisk',
    subcategory: '12v',
    ageGroup: '3-6',
    color: 'blue',
  },
  {
    id: '6',
    name: 'Elektrisk mini ATV for barn 1000W Renegade (grønn)',
    slug: 'elektrisk-mini-atv-for-barn-1000w-renegade-gronn',
    price: 9490,
    salePrice: 8290,
    description: 'Dette er favorittleketøyet for barn og unge. Stor og stødig elektrisk ATV med luftfylte dekk. Leveres med hastighetsbegrensning: Low, medium og high. Firehjulingen stopper automatisk om man faller av. CE og ROHS godkjent.',
    specs: {
      'Motoreffekt': '1000 W',
      'Start': 'El-start',
      'Batteri': '36V 24Ah',
      'Rekkevidde': '20–25 km',
      'Størrelse (LxBxH)': '118×70×67 cm',
      'Dekk foran': '4.10-6',
      'Dekk bak': '13x5.00-6',
      'Bremser': 'Skivebrems',
      'Maks totalbelastning': '65 kg',
      'Maks hastighet': '30 km/h (sperres på 8, 15 og 30 km/h)',
      'Nettovekt': '55 kg',
      'Bruttovekt': '64 kg',
    },
    images: [
      '/images/products/elektrisk-mini-atv-for-barn-500w-green/el_atv_1000w.jpg',
      '/images/products/elektrisk-mini-atv-for-barn-500w-green/el_atv_1000w2.jpg',
      '/images/products/elektrisk-mini-atv-for-barn-500w-green/el_atv_1000w3.jpg',
      '/images/products/elektrisk-mini-atv-for-barn-500w-green/el_atv_20.jpg',
      '/images/products/elektrisk-mini-atv-for-barn-500w-green/el_atv_26.jpg',
    ],
    video: null,
    category: 'elektrisk',
    subcategory: '1000w',
    ageGroup: '7-10',
    color: 'green',
  },
  {
    id: '7',
    name: 'Elektrisk mini ATV for barn 1000W Renegade (rød)',
    slug: 'elektrisk-mini-atv-for-barn-1000w-renegade-rod',
    price: 9490,
    salePrice: 8290,
    description: 'Dette er favorittleketøyet for barn og unge. Stor og stødig elektrisk ATV med luftfylte dekk. Leveres med hastighetsbegrensning: Low, medium og high. Firehjulingen stopper automatisk om man faller av. CE og ROHS godkjent.',
    specs: {
      'Motoreffekt': '1000 W',
      'Start': 'El-start',
      'Batteri': '36V 24Ah',
      'Rekkevidde': '20–25 km',
      'Størrelse (LxBxH)': '118×70×67 cm',
      'Bremser': 'Skivebrems',
      'Maks totalbelastning': '65 kg',
      'Maks hastighet': '30 km/h (sperres på 8, 15 og 30 km/h)',
      'Nettovekt': '55 kg',
      'Bruttovekt': '64 kg',
    },
    images: [
      '/images/products/elektrisk-mini-atv-for-barn-500w-red/el_atv_1000wred.jpg',
      '/images/products/elektrisk-mini-atv-for-barn-500w-red/el_atv_1000wred2.jpg',
      '/images/products/elektrisk-mini-atv-for-barn-500w-red/el_atv_1000wred3.jpg',
      '/images/products/elektrisk-mini-atv-for-barn-500w-red/el_atv_1000w7.jpg',
    ],
    video: null,
    category: 'elektrisk',
    subcategory: '1000w',
    ageGroup: '7-10',
    color: 'red',
  },
  {
    id: '8',
    name: 'Farmer mini ATV 50cc (blå)',
    slug: 'farmer-mini-atv-50cc-bla',
    price: 7990,
    salePrice: 6990,
    description: 'Farmer mini ATV er trolig en av de beste mini firhjulingene vi har testet. Stilig, kompakt og av meget god kvalitet. Denne modellen har easy start for at selv minstemann enkelt skal kunne starte opp sin ATV uten å få hjelp av en voksen. Leveres med justerbar maksfart 0–40 km/h.',
    specs: {
      'Motor': '50cc 2-takts luftkjølt',
      'Bensintank': '2 liter',
      'Gir': 'Automatgir med slureclutch',
      'Drivverk': 'Kjededrift',
      'Bremser': 'Mekaniske skivebremser foran og bak',
      'Startsystem': 'Drasnor (easy start)',
      'Nettovekt': '43,6 kg',
      'Maks belastning': '65 kg',
      'Maks hastighet': '0–40 km/h (justerbar)',
    },
    images: [
      '/images/products/farmer-mini-atv-49cc-for-barn-blue/farmer_49cc_atv_blue.jpg',
      '/images/products/farmer-mini-atv-49cc-for-barn-blue/farmer_49cc_atv_blue2.jpg',
      '/images/products/farmer-mini-atv-49cc-for-barn-blue/farmer_49cc_atv_blue3.jpg',
      '/images/products/farmer-mini-atv-49cc-for-barn-blue/farmer_49cc_atv_blue4.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '50cc',
    ageGroup: '3-6',
    color: 'blue',
  },
  {
    id: '9',
    name: 'Farmer mini ATV 50cc (grønn)',
    slug: 'farmer-mini-atv-50cc-gronn',
    price: 7990,
    salePrice: 6990,
    description: 'Farmer mini ATV er trolig en av de beste mini firhjulingene vi har testet. Stilig, kompakt og av meget god kvalitet. Denne modellen har easy start for at selv minstemann enkelt skal kunne starte opp sin ATV uten å få hjelp av en voksen. Leveres med justerbar maksfart 0–40 km/h.',
    specs: {
      'Motor': '50cc 2-takts luftkjølt',
      'Bensintank': '2 liter',
      'Gir': 'Automatgir med slureclutch',
      'Drivverk': 'Kjededrift',
      'Bremser': 'Mekaniske skivebremser foran og bak',
      'Startsystem': 'Drasnor (easy start)',
      'Nettovekt': '43,6 kg',
      'Maks belastning': '65 kg',
      'Maks hastighet': '0–40 km/h (justerbar)',
    },
    images: [
      '/images/products/farmer-mini-atv-49cc-for-barn-green/farmer_49cc_atv_green.jpg',
      '/images/products/farmer-mini-atv-49cc-for-barn-green/farmer_49cc_atv_green2.jpg',
      '/images/products/farmer-mini-atv-49cc-for-barn-green/farmer_49cc_atv_green3.jpg',
      '/images/products/farmer-mini-atv-49cc-for-barn-green/farmer_49cc_atv_green4.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '50cc',
    ageGroup: '3-6',
    color: 'green',
  },
  {
    id: '10',
    name: 'Farmer mini ATV 50cc (rød)',
    slug: 'farmer-mini-atv-50cc-rod',
    price: 7990,
    salePrice: 6990,
    description: 'Farmer mini ATV er trolig en av de beste mini firhjulingene vi har testet. Stilig, kompakt og av meget god kvalitet. Denne modellen har easy start for at selv minstemann enkelt skal kunne starte opp sin ATV uten å få hjelp av en voksen. Leveres med justerbar maksfart 0–40 km/h.',
    specs: {
      'Motor': '50cc 2-takts luftkjølt',
      'Bensintank': '2 liter',
      'Gir': 'Automatgir med slureclutch',
      'Bremser': 'Mekaniske skivebremser foran og bak',
      'Startsystem': 'Drasnor (easy start)',
      'Nettovekt': '43,6 kg',
      'Maks hastighet': '0–40 km/h (justerbar)',
    },
    images: [
      '/images/products/farmer-mini-atv-49cc-for-barn-red/farmer_49cc_atv_red.jpg',
      '/images/products/farmer-mini-atv-49cc-for-barn-red/farmer_49cc_atv_red1.jpg',
      '/images/products/farmer-mini-atv-49cc-for-barn-red/farmer_49cc_atv_red2.jpg',
      '/images/products/farmer-mini-atv-49cc-for-barn-red/farmer_49cc_atv_red3.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '50cc',
    ageGroup: '3-6',
    color: 'red',
  },
  {
    id: '11',
    name: 'Mini ATV 50cc black edition two',
    slug: 'mini-atv-50cc-black-edition-two',
    price: 6990,
    salePrice: 5990,
    description: 'Vår meget populære mini ATV 50cc kommer nå i oppgradert versjon. Mini ATV Black Edition Two er oppgradert med semiautomatisk girkasse og er blant markedets mest driftsikre mini atv modeller. Leveres med dødmannsstopp og justerbar maksfart.',
    specs: {
      'Motor': '49cc luftkjølt High Performance 2-takt',
      'Startmetode': 'Drasnor med easy start',
      'Maks effekt': '2,5 kW / 8000 r/min',
      'Drivstofftank': '1,0 L',
      'Bremser foran': 'Borede skivebremser',
      'Bremser bak': 'Boret skivebrems (håndbremsespak)',
      'Maks hastighet': '45 km/h',
      'Maks belastning': '50 kg',
      'Bruttovekt': '42 kg',
    },
    images: [
      '/images/products/kj-p-mini-atv-49cc-50cc-black-edition-two-salg-online-engros-service/mini_atv_black.jpg',
      '/images/products/kj-p-mini-atv-49cc-50cc-black-edition-two-salg-online-engros-service/mini_atv_49c.jpg',
      '/images/products/kj-p-mini-atv-49cc-50cc-black-edition-two-salg-online-engros-service/mini_atv_49ccc.jpg',
      '/images/products/kj-p-mini-atv-49cc-50cc-black-edition-two-salg-online-engros-service/c76928fd-662e-4077-b254-0b0342a7d276.jpeg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '50cc',
    ageGroup: '3-6',
    color: 'black',
  },
  {
    id: '12',
    name: 'Outback 110cc ATV med revers (oransje)',
    slug: 'outback-110cc-atv-med-revers-oransje',
    price: 14990,
    salePrice: 12990,
    description: 'Nye Outback 110cc har ankommet vårt lager — vår bestselger gjennom mange år. Mancini Outback er en ATV for barn og ungdom i alderen 7 til 13 år. Den er meget tøff og konstruert for å tåle hard påkjenning, med kraftige dempere og forsterket chassi. Leveres med halvautomatisk girkasse med revers og dødmannsfunksjon.',
    specs: {
      'Motor': '110cc 4-takts luftkjølt',
      'Girkasse': 'Halvautomatisk med revers',
      'Drivverk': 'Kjededrift',
      'Bensintank': '3,2 L',
      'Startsystem': 'Elstart',
      'Maks hastighet': 'ca. 65 km/h (justerbar)',
      'Bremser bak': 'Skivebremser',
      'Bæreevne': '130 kg',
      'Fordekk': '16×8-7',
      'ATV dimensjon (LxBxH)': '138×75×90 cm',
      'Nettovekt': '90 kg',
    },
    images: [
      '/images/products/mancini-outback-110cc-atv-firehjuling-orange/oransje_atv_1.jpg',
      '/images/products/mancini-outback-110cc-atv-firehjuling-orange/oransje_atv_2.jpg',
      '/images/products/mancini-outback-110cc-atv-firehjuling-orange/oransje_atv3.jpg',
      '/images/products/mancini-outback-110cc-atv-firehjuling-orange/oransje_atv_4.jpg',
      '/images/products/mancini-outback-110cc-atv-firehjuling-orange/oransje_atv5.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '110cc',
    ageGroup: '7-10',
    color: 'orange',
  },
  {
    id: '13',
    name: 'Outback 110cc ATV (hvit)',
    slug: 'outback-110cc-atv-hvit',
    price: 14990,
    salePrice: 12990,
    description: 'Mancini Outback er en ATV for barn og ungdom i alderen 7 til 13 år. Den er meget tøff og konstruert for å tåle hard påkjenning, med kraftige dempere og forsterket chassi. Justerbar maksfart og dødmannsfunksjon. Vi har delelager og serviceapparat til alle våre produkter.',
    specs: {
      'Motor': '110cc 4-takts luftkjølt',
      'Girkasse': 'Helautomatisk',
      'Drivverk': 'Kjededrift',
      'Bensintank': '3,2 L',
      'Startsystem': 'Elstart',
      'Maks hastighet': '6–70 km/h (justerbar)',
      'Bæreevne': '130 kg',
      'ATV dimensjon (LxBxH)': '138×75×90 cm',
      'Vekt': '110 kg',
    },
    images: [
      '/images/products/mancini-outback-110cc-atv-og-firehjulinger-white/070d9984-5865-44d0-a81d-363ebab5ca66.jpeg',
      '/images/products/mancini-outback-110cc-atv-og-firehjulinger-white/4d9b417e-a45a-4c56-8e45-74d53017e1a3.jpeg',
      '/images/products/mancini-outback-110cc-atv-og-firehjulinger-white/1a442ec4-bd4a-4247-98fe-e169a6f603b3.jpeg',
      '/images/products/mancini-outback-110cc-atv-og-firehjulinger-white/56041e47-fe67-4315-9fa7-02aa371a93be.jpeg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '110cc',
    ageGroup: '7-10',
    color: 'white',
  },
  {
    id: '14',
    name: 'Challenge ATV 110CC Black Edition',
    slug: 'challenge-atv-110cc-black-edition',
    price: 12990,
    salePrice: 10990,
    description: 'Den ultimate ATV for barn med svært stilig design og mye utstyr. Firehjulingen passer utmerket for aldersgruppen fra 5–10 år. Leveres med dødmannsknapp, justerbar maksfart, håndbeskyttere, hengerkule og speedometer. Semiautomatisk girkasse uten clutch.',
    specs: {
      'Motoreffekt': '7,5 hk luftavkjølt 4-takt',
      'Start': 'Elektrisk start',
      'Tenning': 'CDI',
      'Hengerfeste med kule': 'Ja (maks 25 kg last)',
      'Speedometer': 'Ja',
      'Håndbeskyttere': 'Ja',
      'Kraftoverføring': 'Automatisk med revers',
      'Brems foran': 'Trommelbremser',
      'Brems bak': 'Hydraulisk skivebrems 155mm / 6"',
      'Størrelse montert (LxBxH)': '1200×790×770 mm',
      'Setehøyde': '480 mm',
      'Maks hastighet': '6–50 km/t',
    },
    images: [
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-black/atv110cc15.jpg',
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-black/atv110cc16.jpg',
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-black/atv110cc17.jpg',
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-black/atv110cc18.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '110cc',
    ageGroup: '7-10',
    color: 'black',
  },
  {
    id: '15',
    name: 'Challenge ATV 110CC Green Edition',
    slug: 'challenge-atv-110cc-green-edition',
    price: 12990,
    salePrice: 10990,
    description: 'Den ultimate ATV for barn med svært stilig design og mye utstyr. Firehjulingen passer utmerket for aldersgruppen fra 5–10 år. Leveres med dødmannsknapp, justerbar maksfart, håndbeskyttere, hengerkule og speedometer. Semiautomatisk girkasse uten clutch.',
    specs: {
      'Motoreffekt': '7,5 hk luftavkjølt 4-takt',
      'Start': 'Elektrisk start',
      'Kraftoverføring': 'Automatisk med revers',
      'Brems foran': 'Trommelbremser',
      'Brems bak': 'Hydraulisk skivebrems 155mm / 6"',
      'Størrelse montert (LxBxH)': '1200×790×770 mm',
      'Setehøyde': '480 mm',
      'Maks hastighet': '6–50 km/t',
    },
    images: [
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-green/atv110cc10.jpg',
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-green/atv110cc11.jpg',
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-green/atv110cc12.jpg',
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-green/atv110cc13.jpg',
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-green/atv110cc14.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '110cc',
    ageGroup: '7-10',
    color: 'green',
  },
  {
    id: '16',
    name: 'Mancini Pioner ATV 110CC (oransje)',
    slug: 'mancini-pioner-atv-110cc-oransje',
    price: 10990,
    salePrice: 9990,
    description: 'Den ultimate ATV for barn med svært stilig design. Firehjulingen passer utmerket for aldersgruppen fra 5–10 år. Leveres med dødmannsknapp og justerbar maksfart. ATV-en kan strupes ned til 6 km/t.',
    specs: {
      'Motoreffekt': '7,5 hk',
      'Start': 'Elektrisk start',
      'Kraftoverføring': 'Automatisk uten revers',
      'Brems foran': 'Trommelbrems',
      'Brems bak': 'Skivebrems 155mm / 6"',
      'Størrelse (LxBxH)': '1420×570×900 mm',
      'Setehøyde': '650 mm',
      'Maks hastighet': '6–60 km/t',
    },
    images: [
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-orange/1fd4a457-42f5-42aa-b4dc-e08eec75ef23.jpeg',
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-orange/1d9d53fe-90f4-4b52-a379-a706128764de.jpeg',
      '/images/products/mancini-pioner-110cc-den-ultimate-barne-atv-med-stilig-design-orange/caf5a488561af1c016a4ef1748698cbd.jpeg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '110cc',
    ageGroup: '7-10',
    color: 'orange',
  },
  {
    id: '17',
    name: 'Mini ATV 50cc Green edition two',
    slug: 'mini-atv-50cc-green-edition-two',
    price: 6990,
    salePrice: 5990,
    description: 'Oppgradert mini ATV med semiautomatisk girkasse og easy start — blant markedets mest driftsikre mini ATV-modeller. Leveres med dødmannsstopp og justerbar maksfart.',
    specs: {
      'Motor': 'Luftkjølt High Performance 2-takt 49cc',
      'Startmetode': 'Drasnor med easy start',
      'Justerbar topphastighet': '5–45 km/t',
      'Bremser': 'Skivebremser foran og bak',
      'Setehøyde': '54 cm',
      'Bruttovekt': '42 kg',
    },
    images: [
      '/images/products/mini-atv-50cc-green-edition-two/atv_gr_nn.jpg',
      '/images/products/mini-atv-50cc-green-edition-two/mini_atv_barn.jpg',
      '/images/products/mini-atv-50cc-green-edition-two/mini_atv_barn_3.jpg',
      '/images/products/mini-atv-50cc-green-edition-two/mini_atv_barn_4.jpg',
      '/images/products/mini-atv-50cc-green-edition-two/mini_atv_barn5.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '50cc',
    ageGroup: '3-6',
    color: 'green',
  },
  {
    id: '18',
    name: 'Mini ATV 50cc pink edition two',
    slug: 'mini-atv-50cc-pink-edition-two',
    price: 6990,
    salePrice: 5990,
    description: 'Vår populære mini ATV 50cc i rosa utgave. Leveres med dødmannsstopp og justerbar maksfart — perfekt for de minste som vil ha sin egen ATV.',
    specs: {
      'Motor': 'Luftkjølt High Performance 2-takt 49cc',
      'Startmetode': 'Drasnor med easy start',
      'Justerbar topphastighet': '5–45 km/t',
      'Bremser': 'Skivebremser foran og bak',
      'Setehøyde': '54 cm',
      'Bruttovekt': '42 kg',
    },
    images: [
      '/images/products/mini-atv-50cc-pink-edition-two/mini_atv_rosa1.jpg',
      '/images/products/mini-atv-50cc-pink-edition-two/mini_atv_rosa2.jpg',
      '/images/products/mini-atv-50cc-pink-edition-two/mini_atv_rosa3.jpg',
      '/images/products/mini-atv-50cc-pink-edition-two/mini_atv_rosa4.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '50cc',
    ageGroup: '3-6',
    color: 'pink',
  },
  {
    id: '19',
    name: 'Mini ATV firehjuling for barn 49cc (rød)',
    slug: 'mini-atv-firehjuling-for-barn-49cc-rod',
    price: 6990,
    salePrice: 5990,
    description: 'Vår meget populære mini ATV 50cc i oppgradert versjon med semiautomatisk girkasse — blant markedets mest driftsikre mini ATV-modeller. Leveres med dødmannsstopp og justerbar maksfart. Med easy start vil du enkelt kunne starte opp uten problemer.',
    specs: {
      'Motor': 'Luftkjølt High Performance 2-takt 49cc',
      'Startmetode': 'Drasnor med easy start',
      'Girkasse': 'Semiautomatisk',
      'Bremser': 'Borede skivebremser foran og bak',
      'Topphastighet': '45 km/t',
      'Maks belastning': '50 kg',
      'Bruttovekt': '42 kg',
    },
    images: [
      '/images/products/mini-atv-firehjuling-for-barn-49cc/ed2_red-black.jpg',
      '/images/products/mini-atv-firehjuling-for-barn-49cc/ed2_red-black-1.jpg',
      '/images/products/mini-atv-firehjuling-for-barn-49cc/ed2_red-black-2.jpg',
      '/images/products/mini-atv-firehjuling-for-barn-49cc/ed2_red-black-3.jpg',
      '/images/products/mini-atv-firehjuling-for-barn-49cc/ed2_red-black-4.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '50cc',
    ageGroup: '3-6',
    color: 'red',
  },
  {
    id: '20',
    name: 'Renegade el ATV kardang børsteløs 1200W (grønn)',
    slug: 'renegade-el-atv-kardang-borstelos-1200w-gronn',
    price: 12990,
    salePrice: 9990,
    description: 'Renegade el ATV med børsteløs 1200W motor, 48V og kardangdrift. Kraftigste på markedet i sin størrelse. Innbygget fartssperre som kan låses til tre hastigheter: 12 km/t, 25 km/t og topphastighet 40 km/t. Nesten 100% lydløs — suveren på alle underlag som gress, grus, stein, jord og snø.',
    specs: {
      'Motor': 'Børsteløs 1200W 48V',
      'Batteri': '48V 12Ah Lead Acid (4 × 12V 12Ah)',
      'Hastighet': '12–40 km/t (3 nivåer med nøkkel)',
      'Rekkevidde': '30–35 km',
      'Anbefalt alder': 'Fra 7 år',
      'Drift': 'Kardangdrift (Shaft Drive)',
      'Fordekk': '145/70-6"',
      'Bakdekk': '145/70-6"',
      'Forbremse': 'Tromlebremse',
      'Bakbremse': 'Hydraulisk skivebremse',
      'Lys': 'Double front LED og baklys',
      'Nettovekt': '73 kg',
      'Maks førersvekt': '95 kg',
    },
    images: [
      '/images/products/renegade-el-atv-kardang-b-rstel-s-1200w-green/el_atv_1200w1.jpg',
      '/images/products/renegade-el-atv-kardang-b-rstel-s-1200w-green/el_atv_1200w2.jpg',
      '/images/products/renegade-el-atv-kardang-b-rstel-s-1200w-green/el_atv_1200w3.jpg',
    ],
    video: 'https://www.youtube.com/embed/AjJBaU4lk_s',
    category: 'elektrisk',
    subcategory: '1200w',
    ageGroup: '7-10',
    color: 'green',
  },
  {
    id: '21',
    name: 'Renegade el ATV kardang børsteløs 1200W (rød)',
    slug: 'renegade-el-atv-kardang-borstelos-1200w-rod',
    price: 12990,
    salePrice: 9990,
    description: 'Renegade el ATV med børsteløs 1200W motor, 48V og kardangdrift. Kraftigste på markedet i sin størrelse. Innbygget fartssperre som kan låses til tre hastigheter: 12 km/t, 25 km/t og topphastighet 40 km/t. Nesten 100% lydløs — suveren på alle underlag som gress, grus, stein, jord og snø.',
    specs: {
      'Motor': 'Børsteløs 1200W 48V',
      'Batteri': '48V 12Ah Lead Acid (4 × 12V 12Ah)',
      'Hastighet': '12–40 km/t (3 nivåer med nøkkel)',
      'Rekkevidde': '30–35 km',
      'Anbefalt alder': 'Fra 7 år',
      'Drift': 'Kardangdrift (Shaft Drive)',
      'Forbremse': 'Tromlebremse',
      'Bakbremse': 'Hydraulisk skivebremse',
      'Nettovekt': '73 kg',
      'Maks førersvekt': '95 kg',
    },
    images: [
      '/images/products/renegade-el-atv-kardang-b-rstel-s-1200w-red/el_atv_1200wred.jpg',
      '/images/products/renegade-el-atv-kardang-b-rstel-s-1200w-red/el_atv_1200wred1.jpg',
      '/images/products/renegade-el-atv-kardang-b-rstel-s-1200w-red/el_atv_1200wred2.jpg',
    ],
    video: 'https://www.youtube.com/embed/AjJBaU4lk_s',
    category: 'elektrisk',
    subcategory: '1200w',
    ageGroup: '7-10',
    color: 'red',
  },
  {
    id: '22',
    name: 'Tøff elektrisk barne ATV 6V',
    slug: 'toff-elektrisk-barne-atv-6v',
    price: 1399,
    salePrice: 899,
    description: 'El mini ATV for de minste. Nå kan barna oppleve den morsomme opplevelsen av å kjøre firehjuling. Denne kule firehjulingen leveres med 6V batteri og motor med revers.',
    specs: {
      'Motor': '20W',
      'Batteri': '6V 4A',
      'Hastighet': '2,8–4,6 km/t',
      'Ladetid': '8–12 timer',
      'Kjøretid': '50–60 minutter',
      'Gir': 'Forover og bakover',
      'Lastekapasitet': '30 kg',
      'Anbefalt alder': '2,5+ år',
      'Nettovekt': '4,6 kg',
    },
    images: [
      '/images/products/t-ff-elektrisk-barne-atv-6v/speed22.jpg',
      '/images/products/t-ff-elektrisk-barne-atv-6v/speed24.jpg',
      '/images/products/t-ff-elektrisk-barne-atv-6v/speed25.jpg',
      '/images/products/t-ff-elektrisk-barne-atv-6v/speed27.jpg',
    ],
    video: null,
    category: 'elektrisk',
    subcategory: '6v',
    ageGroup: '3-6',
    color: 'green',
  },
  {
    id: '23',
    name: 'YOKI 450CC BEAST lang utgave',
    slug: 'yoki-450cc-beast-lang-utgave',
    price: 56990,
    salePrice: null,
    description: 'Norgesnyheten YOKI Beast 450cc — registreres som klasse T3B og kjøres med klasse B sertifikat. Kraftig, prisgunstig og fullspekket firehjuling med moderne teknologi, rå ytelse og slitesterk konstruksjon. Montering inklusiv skilt kr 3 900.',
    specs: {
      'Registrering': 'Klasse T3B (kjøres med klasse B sertifikat)',
      'Motor': 'Ensylinder, vannkjølt, firetakt',
      'Slagvolum': '391cc',
      'Maks effekt': '20 kW / 6500 o/min',
      'Girkasse': 'Automatisk CVT',
      'Trekkraft': '4WD',
      'Bremser': 'Skivebremser foran og bak',
      'Bakkeklaring': '250 mm',
      'Vekt': '353 kg',
      'Lastekapasitet': '240 kg',
      'Drivstofftank': '17 L',
      'Toppfart': '60 km/t',
      'Dimensjon (LxBxH)': '2315×1144×1340 mm',
    },
    images: [
      '/images/products/yoki-450cc-beast-lang-utgave-black/yokib450l.png',
      '/images/products/yoki-450cc-beast-lang-utgave-black/atv1_2.png',
      '/images/products/yoki-450cc-beast-lang-utgave-black/atv5.jpg',
      '/images/products/yoki-450cc-beast-lang-utgave-black/atv6.jpg',
      '/images/products/yoki-450cc-beast-lang-utgave-black/atv8.jpg',
    ],
    video: null,
    category: 'bensindrevet',
    subcategory: '450cc',
    ageGroup: 'voksen',
    color: 'black',
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category)
}

export function getProductsBySubcategory(subcategory: string): Product[] {
  return products.filter(p => p.subcategory === subcategory)
}

export function getProductsByAgeGroup(ageGroup: string): Product[] {
  return products.filter(p => p.ageGroup === ageGroup)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter(p => p.slug !== product.slug && (p.category === product.category || p.ageGroup === product.ageGroup))
    .slice(0, limit)
}

export function formatPrice(price: number): string {
  return `kr ${price.toLocaleString('nb-NO')}`
}
